### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by HiddenApache** [jasonsworks/cod-scripts#1]
After placing the main.gsc in the specified location for plutonium scripts, I receive the following:

[ERROR]:compiler:scripts/zm/zm_prison/main.gsc:7:1:syntax error, unexpected <

![image](https://github.com/user-attachments/assets/72d091d5-9ae5-48fa-b797-fa5ccd8a10f3)

**Comment by HiddenApache** [comment]
Nevermind, I'm a dumbass

**Comment by jasonsworks** [comment]
Haha I was literally just reinstalling the game to see what the issue was, I'm surprised you even found this repo.
